### ISSUE TITLE
TypeError: list indices must be integers or slices, not SecretSantaConstants

### ISSUE THREAD

**Issue by irnutsmurt** [avchikar97/SantaBot#49]
Bot keeps crashing. I believe its after trying to select a wishlist when this happened. Originally got the error in Discord after adding the wishlist
ERROR: invalid input.

Then the bot crashed. Trying to bring it back up I get the error below in the logs

usr = SecretSantaParticipant(data[SecretSantaConstants.NAME], data[SecretSantaConstants.DISCRIMINATOR], data[SecretSantaConstants.IDSTR], data[SecretSantaConstants.USRNUM], data[SecretSantaConstants.WISHLISTURL], data[SecretSantaConstants.PREFERENCES], data[SecretSantaConstants.PARTNERID])
TypeError: list indices must be integers or slices, not SecretSantaConstants

**Comment by avchikar97** [comment]
Should be fixed now (along with bugs that would have made setting preferences fail every time)

Let me know if it works or if you still have problems

**Comment by irnutsmurt** [comment]
Thank you for the quick fix, everything is now working properly.
