### ISSUE TITLE
User Story: Ability for the Bot to send a question to whoever they have for secret santa

### ISSUE THREAD

**Issue by irnutsmurt** [avchikar97/SantaBot#56]
As a participant in Secret Santa, I want the ability to send a message to whoever I have for Secret Santa to ask them a question if I need some sort of detail through the bot so I that I can not reveal who I have.

**Comment by avchikar97** [comment]
Maybe something like` s!dmsanta` to have the bot DM the person that has you and `s!dmpartner` to have the bot DM you have?

Ideas for command names welcome

**Comment by irnutsmurt** [comment]
I think dmpartner works.

**Comment by avchikar97** [comment]
This functionality should be fully implemented with the patch referenced above

Since this is a new type of functionality for me to be implementing, I'd like to keep this issue open for a while in case there are any problems or related design needs

**Comment by irnutsmurt** [comment]
The DM works back and forth. I would add confirmation message has been sent so people know when it is.

**Comment by avchikar97** [comment]
Feature implemented - if there are any problems open a new issue
